name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: |
        npm install
        npm install -g node-pre-gyp

    - name: Build
      run: npm run build

    - name: Package binary
      run: |
        node-pre-gyp package
        ls -la build/stage || true
        find . -name "*.tar.gz" || true

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/**/*.tar.gz
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

    - name: Publish to npm
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}